# Generated by Django 3.0.2 on 2020-03-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Document_image',
            field=models.FileField(upload_to=''),
        ),
    ]
